### ISSUE TITLE
Bug in GeoUMount

### ISSUE THREAD

**Issue by wweicht** [xahmol/GeoUTools#5]
There is a bug in GeoUMount
The program does not show files on 1541UII+, that have a unset Archive bit.

Look also at https://www.forum64.de/index.php?thread/148873-fragen-tips-zu-geoutools/&postID=2173746#post2173746 and following messages.

**Comment by xahmol** [comment]
Thanks!
Will not be able to look at it for the next three weeks as I am on a holiday, but will definitely look into that.

Xander

**Comment by wweicht** [comment]
No problem. Happy holiday

wweicht

**Comment by xahmol** [comment]
Bug fix committed.

I could reproduce error myself by clearing archive bit on a file, the fix appears to solve the issue.

https://github.com/xahmol/GeoUTools/commit/94b59b915fb615f047038a09684b0125e1ed1788

**Comment by wweicht** [comment]
Bug is fixed. Thanks.

Bye
Werner
